aider: Fix Bip44PublicKey method for P2SH address types to use Bip49PublicKey.
# Aider chat conversation:

USER: @BenGWeeks ➜ /workspaces/seedphrase-fixer (main) $ python main.py "expect fringe deer battle junior sample trap thunder wrong gesture neck pipe" "" 1
Traceback (most recent call last):
  File "/workspaces/seedphrase-fixer/main.py", line 34, in <module>
    main()
  File "/workspaces/seedphrase-fixer/main.py", line 17, in main
    corrected_seedphrase, balances = fix_seedphrase(args.seedphrase, args.passphrase, args.replace_index)
  File "/workspaces/seedphrase-fixer/utils/seedphrase_fixer.py", line 13, in fix_seedphrase
    addresses = derive_multiple_address_types(seedphrase, passphrase)
  File "/workspaces/seedphrase-fixer/utils/address_derivation.py", line 29, in derive_multiple_address_types
    'P2SH': derive_address_from_seed(seed_bytes, 'P2SH'),
  File "/workspaces/seedphrase-fixer/utils/address_derivation.py", line 14, in derive_address_from_seed
    address = bip32_ctx.PublicKey().ToP2shSegwitAddress()
AttributeError: 'Bip44PublicKey' object has no attribute 'ToP2shSegwitAddress'

ASSISTANT: The error message indicates that the 'Bip44PublicKey' object does not have a 'ToP2shSegwitAddress' method. This is likely because the Bip44PublicKey object is not intended to be used for P2SH address types.

The Bip49 standard should be used for P2SH address types. Therefore, the 'derive_address_from_seed' function in the 'utils/address_derivation.py' file should be modified to use the Bip49PublicKey object for P2SH address types.

Here is the *SEARCH/REPLACE* block:

utils/address_derivation.py
```python
<<<<<<< SEARCH
elif address_type == 'P2SH':
    bip32_ctx = Bip49.FromSeed(seed_bytes, Bip49Coins.BITCOIN)
    bip32_ctx = bip32_ctx.Purpose().Coin().Account(0).Change(Bip44Changes.CHAIN_EXT).AddressIndex(0)
    address = bip32_ctx.PublicKey().ToP2shSegwitAddress()
=======
elif address_type == 'P2SH':
    bip32_ctx = Bip49.FromSeed(seed_bytes, Bip49Coins.BITCOIN)
    bip32_ctx = bip32_ctx.Purpose().Coin().Account(0).Change(Bip44Changes.CHAIN_EXT).AddressIndex(0)
    address = bip32_ctx.PublicKey().ToAddress()
>>>>>>> REPLACE
```
This change will ensure that the correct method is called on the Bip49PublicKey object to derive the P2SH address.